config/routes.rb
Mandala::Application.routes.draw do
  resources :details

  resources :phrases

  resources :passages

  match '(/:title)(.:format)'=> 'passages#show'
  match 'details(/:keyword)/:id(.:format)'=> 'details#show'
  root to: "passages#index", id: 1

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  attr_accessible :content, :keyword, :phrase_id
  belongs_to :phrase

end

app/models/passage.rb
class Passage < ActiveRecord::Base
  attr_accessible :damage, :population, :title, :phrases_attributes

  has_many :phrases
  accepts_nested_attributes_for :phrases

  before_create :default_values

  validates :title, uniqueness: true

  def receives_damage
    self.damage += 1

    self.phrases.each do |phrase|
      phrase.clear_phrase if phrase.should_be_blank_after? self.damage
    end

    self.save
  end

  # a method like this may be necessary
  # def self.phrases
  #  phrases = super
  #
  #  return phrases.order(:id)
  # end

  private
  def default_values
    self.population ||= 0
    self.damage ||= 0

  end
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  attr_accessible :content, :hit_points, :blank, :details_attributes
  belongs_to :passage

  before_create :default_values

  has_many :details
  accepts_nested_attributes_for :details

  # returns the opacity at which this phrase should be displayed,
  # as calculated by its damage rating
  def opacity
    hit_points_left = self.hit_points - self.passage.damage
    ratio = hit_points_left / self.hit_points.to_f

    return [ratio, 0].max.to_s
  end

  def clear_phrase
    self.blank = true
    self.content = self.content.gsub(/./, "&nbsp;")

    self.save
  end

  def should_be_blank_after?(damage)
    !self.blank && self.hit_points <= damage
  end

  private

  def default_values
    self.hit_points ||= 1000

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  # GET /details/1
  # GET /details/1.json
  def show
    # should be Passage.find_by_id.phrases.find_by_id.details.find_by_keyword or something maybe?
    @phrase = Phrase.find_by_id(params[:id])
    @detail = @phrase.details.find_by_keyword(URI.unescape(params[:keyword]))

    respond_to do |format|
      format.html { render layout: false }# show.html.erb
      format.json { render json: @detail }
    end
  end

end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  # GET /passages
  # GET /passages.json
  def index
    @passage = Passage.find(params[:id])
    @passage.receives_damage

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passages }
    end
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
    @passage = Passage.find_by_title!(URI.unescape(params[:title]))
    @passage.receives_damage

    respond_to do |format|
      format.html { render layout: false } # show.html.erb
      format.json { render json: @passage }
    end
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/details/_form.html.haml
= form_for @detail do |f|
  - if @detail.errors.any?
    #error_explanation
      %h2= "#{pluralize(@detail.errors.count, "error")} prohibited this detail from being saved:"
      %ul
        - @detail.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :keyword
    = f.text_field :keyword
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :phrase_id
    = f.number_field :phrase_id
  .actions
    = f.submit 'Save'

app/views/details/edit.html.haml
%h1 Editing detail

= render 'form'

= link_to 'Show', @detail
\|
= link_to 'Back', details_path

app/views/details/index.html.haml
%h1 Listing details

%table
  %tr
    %th Keyword
    %th Content
    %th Phrase
    %th
    %th
    %th

  - @details.each do |detail|
    %tr
      %td= detail.keyword
      %td= detail.content
      %td= detail.phrase_id
      %td= link_to 'Show', detail
      %td= link_to 'Edit', edit_detail_path(detail)
      %td= link_to 'Destroy', detail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Detail', new_detail_path

app/views/details/new.html.haml
%h1 New detail

= render 'form'

= link_to 'Back', details_path

app/views/details/show.html.haml
%p{ class: @detail.keyword }
  = @detail.content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mandala</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/passages/_form.html.haml
= form_for @passage do |f|
  - if @passage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@passage.errors.count, "error")} prohibited this passage from being saved:"
      %ul
        - @passage.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :damage
    = f.number_field :damage
  .field
    = f.label :population
    = f.number_field :population
  .actions
    = f.submit 'Save'

app/views/passages/_show.html.haml
.passage
  %p
    - @passage.phrases.each do |phrase|
      %span{ :id => phrase.id, :style => "opacity: #{ phrase.opacity }" }
        = raw(phrase.content) + " "

app/views/passages/edit.html.haml
%h1 Editing passage

= render 'form'

= link_to 'Show', @passage
\|
= link_to 'Back', passages_path

app/views/passages/index.html.haml
%p#notice= notice

= render partial: "show"

app/views/passages/new.html.haml
%h1 New passage

= render 'form'

= link_to 'Back', passages_path

app/views/passages/show.html.haml
= render partial: "show"

app/views/phrases/_form.html.haml
= form_for @phrase do |f|
  - if @phrase.errors.any?
    #error_explanation
      %h2= "#{pluralize(@phrase.errors.count, "error")} prohibited this phrase from being saved:"
      %ul
        - @phrase.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :hit_points
    = f.number_field :hit_points
  .actions
    = f.submit 'Save'

app/views/phrases/edit.html.haml
%h1 Editing phrase

= render 'form'

= link_to 'Show', @phrase
\|
= link_to 'Back', phrases_path

app/views/phrases/index.html.haml
%h1 Listing phrases

%table
  %tr
    %th Content
    %th Hit points
    %th
    %th
    %th

  - @phrases.each do |phrase|
    %tr
      %td= phrase.content
      %td= phrase.hit_points
      %td= link_to 'Show', phrase
      %td= link_to 'Edit', edit_phrase_path(phrase)
      %td= link_to 'Destroy', phrase, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Phrase', new_phrase_path

app/views/phrases/new.html.haml
%h1 New phrase

= render 'form'

= link_to 'Back', phrases_path

app/views/phrases/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @phrase.content
%p
  %b Hit points:
  = @phrase.hit_points

= link_to 'Edit', edit_phrase_path(@phrase)
\|
= link_to 'Back', phrases_path